Repository usgo/agagd, pull requests merged in 2020-10, with the labels that each got.

#125 Patch fake fixtures
  Dockerfile
  Dockerfile.mysql
  Dockerfile.python3
  agagd/agagd_core/models.py
  agagd/agagd_core/views/core.py
  scripts/entrypoint.sh
  scripts/make_fake_fixtures.py
  sql/most-tournaments-rated-games-12132019.sql
  sql/top-dan-and-kyu-view-12122019.sql
Labels: Type: Maintenance, enhancement, feature request

#129 Include a link to the player's chapter on the member detail page.
  agagd/agagd_core/views/core.py
  agagd/templates/agagd_core/member.html
Labels: feature request

#136 Add missing rating information to the chapter and country pages.
  agagd/agagd_core/views/core.py
Labels: bug

#138 Added Custom Subclass for ChapterColumn.
  agagd/agagd_core/tables.py
Labels: bug, enhancement
